name: Flutter Android Build on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android APK on Windows
    runs-on: ubuntu-latest  # Running on Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Set your Flutter version
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Run Flutter Tests
        run: flutter test

      - name: Set up Java (Required for Android builds)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Using Azul Zulu JDK
          java-version: '17'  # Use Java 17 (required for latest Android builds)

      - name: Accept Android Licenses
        run: flutter doctor --android-licenses

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build App Bundle (AAB)
        run: flutter build appbundle

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
